### ISSUE TITLE
Linux Dockerfile

### ISSUE THREAD

**Issue by styk-tv** [DBraun/DawDreamer#11]
Anyone interested in spending couple of hours in the afternoon on a call doing a screen share trying to figure out a docker container to build/run this?

**Comment by styk-tv** [comment]
I started at the root (RenderMan) just to see how far I can get.

```
root@ubuntu-xenial:~/RenderMan/Builds/LinuxMakefile/build# ls -al
total 45264
drwxr-xr-x 4 root    root        4096 Sep  4 02:23 .
drwxrwxr-x 3 vagrant vagrant     4096 Sep  4 01:36 ..
drwxr-xr-x 3 ubuntu  vboxsf      4096 Sep  4 02:23 Dexed-Nightly
-rwxr-xr-x 1 root    root     9538200 Sep  4 02:23 Dexed.so
-rw-r--r-- 1 root    root     6271657 Aug 20 14:24 Dexed_ubuntu_linux_edc3079-20200820.tgz
drwxr-xr-x 3 root    root        4096 Sep  4 01:36 intermediate
-rwxr-xr-x 1 root    root    30519112 Sep  4 01:37 librenderman.so

root@ubuntu-xenial:~/RenderMan/Builds/LinuxMakefile/build# python
Python 2.7.12 (default, Jul 21 2020, 15:19:50)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import librenderman as rm
JUCE v5.2.0
>>> sampleRate = 44100
>>> bufferSize = 512
>>> fftSize = 512
>>> engine = rm.RenderEngine(sampleRate, bufferSize, fftSize)
>>> engine.load_plugin("Dexed.so")
JUCE Assertion failure in juce_File.cpp:191
Attempting to load VST: /home/vagrant/RenderMan/Builds/LinuxMakefile/build/Dexed.so
JUCE Assertion failure in RenderEngine.cpp:32
Segmentation fault (core dumped)
```

So librenderman seems to load fine in python however loading new Dexed fails probably because it requires new version of Juce.

Would be interesting to update DawDreamer to support Linux compilation options

**Comment by DBraun** [comment]
Thanks for giving this a shot. Starting with Renderman is definitely a good idea. It has the extra baggage of boost, but it looks like you got past that. Your error is at this line https://github.com/fedden/RenderMan/blob/33213e50b7096a419db1186f89a13cceb659d718/Source/RenderEngine.cpp#L32 so I'm not sure what's wrong with the plugin. Can you try an absolute path to the plugin? Also some std::cout messages in loadPlugin.

I'm on Windows, and Projucer can create Visual Studio solutions and Xcode projects. Because I'm not on Linux, I can't easily churn out a Builds/LinuxMakeFile/Makefile. Are you able to use the Projucer on Linux to get a new Makefile, or would it have to be written by hand?

**Comment by styk-tv** [comment]
Thanks for the reply. Confirmation of load above states correct full path so working folder is being translated correctly. I did run it just in case to confirm

```
>>> engine.load_plugin("/home/vagrant/RenderMan/Builds/LinuxMakefile/build/Dexed.so")
Attempting to load VST: /home/vagrant/RenderMan/Builds/LinuxMakefile/build/Dexed.so
```

Could you point me to a binary `.so.` instrument you have verified so we can exlcude it is not a particular `.so` build that's causing the issue

Another thing I've noticed by following default RenderMan obviously this is run with python 2.7.12. I have tried both 3.5.2 and 3.8.5 with the following result:

```
root@ubuntu-xenial:~/RenderMan/Builds/LinuxMakefile/build# python3.8
Python 3.8.5 (default, Jul 20 2020, 19:50:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librenderman as rm
JUCE v5.2.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_librenderman)
>>> import renderman as rm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'renderman'
>>> exit()
```

and

```
root@ubuntu-xenial:~/RenderMan/Builds/LinuxMakefile/build# python3
Python 3.5.2 (default, Jul 17 2020, 14:04:10)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librenderman as rm
JUCE v5.2.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_librenderman)
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
```

Re your environment problem. Both Vagrant and Docker are your friends.  I am testing on mac in a vagrant xenial box (run by virtualbox). You run `vagrant up && vagrant ssh` and 15 sec later you're in linux. My message is focused on `Dockerfile` because the path we discover towards a working version is then not susceptible to environment variations (a.k.a it always works) So going in that direction is preferred both from Travis CI tests and eventual and unavoidable Kubernetes workflows.

For Vagrantfile i use simple config like this:

```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network"
end
```

This gets me to Xenial.

For running of the above i got there by following this installation sequence:

```
apt-get install \
    clang \
    pkg-config \
    libboost-all-dev \
    libboost-python-dev \
    libfreetype6-dev \
    libx11-dev \
    libxinerama-dev \
    libxrandr-dev \
    libxcursor-dev \
    mesa-common-dev \
    libasound2-dev \
    freeglut3-dev \
    libxcomposite-dev \
    libcurl4-gnutls-dev \
    libcurl4-openssl-dev
make --directory=Builds/LinuxMakefile/
```

So my suggestion would be to get VirtualBox, get Vagrant, then use Vagrantfile above, then `vagrant up && vagrant ssh`, then run installation. There we can experiment with different python versions and start building proper environment. To make sure we can codify all the excercises we should systematize inside xenial and add Vagrantfile lines to map to local host. Then keep adding this knowledge both to Vagrantfile (for development) and Dockerfile (for test runs with Travis)

**Comment by styk-tv** [comment]
...and I have tried several audio online groups and asked for someone to share newest Juce Dockerfile. I hardly doubt people are not using it so maybe we will get lucky to push this forward from Juce Makefile perspective as well. Either way it cannot be that difficult when we start, finding time is going forward is the biggest obstacle. But its a noble goal. I seriously have dreams about the day when this is possible. :)

**Comment by guillaumephd** [comment]
In my fork, at https://github.com/guillaumephd/DawDreamer, you can find:

-  a working `Makefile`, to build `DawDreamer` on Linux
-  a working `Dockerfile`, to build a Linux Docker Image with `DawDreamer`

Cheers!

**Comment by turian** [comment]
@guillaumephd do you mind pushing a PR to the main repo?

@styk-tv Here is a working Dockerfile I wrote for renderman and dexed: https://github.com/turian/renderman-dexed-linux

**Comment by DBraun** [comment]
Thanks everyone! I've merged the docker file in. Please open a new issue if something's not working.
