### ISSUE TITLE
Is there any way to set an option inside a VST plugin?

### ISSUE THREAD

**Issue by Centauria** [DBraun/DawDreamer#115]
For example,

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/20443216/187453444-112c87f5-4713-43f6-9db6-c524ef4d5cc0.png">

In Roland TR series VST plugins, there's an option called `Position lock to DAW`, which is enabled by default, enables the automatic playback of the sequencer of the plugin when we hit Playback in the DAW.

BUT, we usually want this feature **disabled** when these plugins are only used as MIDI interpreters in our code. How can we disable this option in our code?

**Comment by DBraun** [comment]
If it doesn't show up in `synth.get_parameters_description()` then there probably isn't a way. You might be able to create one preset with `open_editor()` and `save_state()` that has that feature disabled. Then you could use it as a launching point for creating other settings programatically.
```python
synth.open_editor()  # Open the editor, disable `Position lock to DAW`, and close
synth.save_state('position_lock_disabled.bin')

# elsewhere or in subsequent runs:
synth.load_state('position_lock_disabled.bin')
# do other stuff programatically
synth.set_parameter(1, 0.1234)
```

https://github.com/DBraun/DawDreamer/wiki/Plugin-Processor

**Comment by Centauria** [comment]
As far as I know, the global settings/options of plugins will never show up in parameter descriptions. So I hope DawDreamer can provide an approach for global settings of plugins.

**Comment by DBraun** [comment]
That's true in most cases from what have seen, but did you try what I described with `open_editor()`?
