### ISSUE TITLE
Apple Silicon version fails on DawDreamer 0.6.11

### ISSUE THREAD

**Issue by heqi201255** [DBraun/DawDreamer#124]
I'm using an M1 MacBook with python3.10, I got 
"ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dawdreamer/dawdreamer.so, 0x0002): symbol not found in flat namespace (__Z10DSPToBoxesRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEES7_iPPKcPiSB_RS5_)" when importing dawdreamer version 0.6.11, the issue was resolved after going back to 0.6.10

**Comment by DBraun** [comment]
Good catch thank you! I forgot to make the universal version of libfaust.

**Comment by DBraun** [comment]
Can you check with 0.6.12?

**Comment by heqi201255** [comment]
0.6.12 works perfectly fine, thanks!
