### ISSUE TITLE
.dll equivalent on Mac

### ISSUE THREAD

**Issue by samuelbraun04** [DBraun/DawDreamer#126]
My script currently runs on Windows using the following:

```
...
soft_clipper = engine.make_plugin_processor("my_soft_clipper", r"path\to\Initial Clipper.dll")
...
```

However, since .dll is a Window's exclusive filetype, it doesn't run on Mac. What filetype should Initial Clipper be so that it can run on a Mac? Thank you.

**Comment by DBraun** [comment]
You'll need .vst3.  If necessary you can try to use files that are .vst or .component.
