### ISSUE TITLE
Support for VST2 format on Windows?

### ISSUE THREAD

**Issue by ZhaoJY1** [DBraun/DawDreamer#13]
Hallo,

I want to know whether DawDreamer will support VST2 plug-in format on Windows platform? Because as I know, JUCE has already removed VST2 SDK, and also in your provided VS2019 solution, these following two includes failed (juce_VSTPluginFormat.cpp):
`#include <pluginterfaces/vst2.x/aeffect.h>`
`#include <pluginterfaces/vst2.x/aeffectx.h>`

Actually, I have once successfully built `RenderMan` for Windows and tested it. The built dynamic libarary `librenderman` has no problem to load a VST3 plug-in (which has extension .vst3), but could not load VST2 plug-in (.dll). But my built version of RenderMan is not from original repo but from this [repo](https://github.com/ethman/slakh-generation). 

I see in your example code, you have used plug-in in .dll format, which I think should be a VST2 format, if it is on Windows. So I am really interested to know whether you are sure that DawDreamer supports VST2 plug-ins on Windows. Or if you could tell me why in my buiding trying of DawDreamer, the aforehand include errors happen, it would really be helpful for my project, I have been searching for a command-line python VST-host/DAW for Windows for a long time!!

Thanks, I am fairly a fresh programmer yet.

**Comment by DBraun** [comment]
Hello,

Yes I totally empathize with your question. I spent a huge amount of time wrapping my head around the situation of JUCE removing some essential files. The solution I ended up with, which I think is ok per Github etiquette, is to use a submodule to place the previous version of JUCE in `DawDreamer\thirdparty\JUCE`. Can you confirm that this folder exists in your computer? If not, try cloning the DawDreamer repo in a different way.

DawDreamer definitely supports VST2 instruments/effects (DLL files). I use Windows primarily. I just tested VST3 effects, which work fine. However, I may have overlooked VST3 instruments, which may not be working right now. I'll investigate. Anyway, give it a shot and let me know how it goes!

**Comment by ZhaoJY1** [comment]
> 
> 
> Hello,
> 
> Yes I totally empathize with your question. I spent a huge amount of time wrapping my head around the situation of JUCE removing some essential files. The solution I ended up with, which I think is ok per Github etiquette, is to use a submodule to place the previous version of JUCE in `DawDreamer\thirdparty\JUCE`. Can you confirm that this folder exists in your computer? If not, try cloning the DawDreamer repo in a different way.
> 
> DawDreamer definitely supports VST2 instruments/effects (DLL files). I use Windows primarily. I just tested VST3 effects, which work fine. However, I may have overlooked VST3 instruments, which may not be working right now. I'll investigate. Anyway, give it a shot and let me know how it goes!

**Comment by ZhaoJY1** [comment]
Hello，

you are right, I had just download zip file but not git cloned the repo, so the `thirdparty/JUCE` and 'thirdparty/pybind11` folders are empty.

With git clone, I have successfully built dawdreamer, and tested it. 

But saddly I found that maybe **dawdreamer does not support VST2 Instruments**, which usually have a `.dll` file and a `.instruments` folder with same name. When you try to load it with `synth.make_plugin_processor()', it simply crashes. :(

I don't know whether this would be a commen issue, I just tested it with a instrument plugin called "DSK The Grand", free downloaded from website. 

But still, many thanks to your excellent work!

**Comment by DBraun** [comment]
I just tested DSK The Grand and it works.

Could you replace SYNTH_PLUGIN in this code and let me know what happens?

```python
import numpy as np
from scipy.io import wavfile

import dawdreamer as daw

SAMPLE_RATE = 44100
BUFFER_SIZE = 512
SYNTH_PLUGIN = "C:/VSTPlugIns/DSK The Grand.dll"  # absolute file path, not relative

print('making engine...')
engine = daw.RenderEngine(SAMPLE_RATE, BUFFER_SIZE)

print('making processor...')
synth = engine.make_plugin_processor("synth", SYNTH_PLUGIN)

graph = [
    (synth, []),
]

synth.add_midi_note(60, 127, 0., 1.)  # note, velocity, start time sec, duration sec
synth.add_midi_note(67, 127, 0.5, .25)
print('loading graph...')
assert(engine.load_graph(graph))
print('rendering...')

engine.render(5.)
audio = engine.get_audio()
audio = np.array(audio, np.float32).transpose()
wavfile.write('test_synth_basic.wav', SAMPLE_RATE, audio)

print("All Done!")
```

**Comment by ZhaoJY1** [comment]
Hallo,

thank you so much for such quick response, just feel so appreciated that an active developer helps a freshman programmer!!! 

No problem with VST2 instruments!  It was simply because I didn't use an absolute path pointing to the VST. 

Actually I should have known and tried with absolute path, because I know for `RenderMan`, absolute path is needed. I forgot or ignored this, because before I tried to load the "DSK The Grand" VST2 instrument, I firstly tested loading of the widely used "Kontakt Player" plugin. I used a **relative path** for this plugin and had no problem to load it! (interesting...) So my brain turns to think subconsciously that DawDreamer works fine with relative path. lol.
Maybe for those plugins with only one dll file (e.g. Kontakt.dll), relative path works, but not for those VST instruments with additionaly a folder?

Anyway, thanks again!

**Comment by DBraun** [comment]
Great. I'll make the documentation clearer for this. In my experience it has to be absolute paths. You might also have fun with the parameter automation branch https://github.com/DBraun/DawDreamer/issues/5 If you're curious check it out and report any issues. Thanks!
