### ISSUE TITLE
how can I  load kontakt.dll and load the nki instrument to generate a wav

### ISSUE THREAD

**Issue by GMPHL** [DBraun/DawDreamer#133]
thanks!

**Comment by DBraun** [comment]
There isn't a straightforward way to load an NKI file, but here are two solutions:

1. You can either replace the default `kontakt_def.nkm` on your filesystem and re-create the PluginProcessor.

2. Or you can follow the example ` test_plugin_editor` for Kontakt in https://github.com/DBraun/DawDreamer/blob/main/tests/test_plugins.py
You would use `open_editor`, then select the NKI file, then save the state if necessary. Then on subsequent runs you can optionally re-load the state.

**Comment by GMPHL** [comment]
thank you so much！

**Comment by DBraun** [comment]
Cool, closing as resolved.
