### ISSUE TITLE
VST3 instruments aren't working

### ISSUE THREAD

**Issue by DBraun** [DBraun/DawDreamer#14]
VST3 instruments appear to be crashing when rendering. The plugins load fine but the processor crashes on `myPlugin->processBlock` inside `PluginProcessor.cpp`. https://github.com/DBraun/DawDreamer/blob/4b3fae94b9f09c9cd306a0782daa69a04a94078c/Source/PluginProcessor.cpp#L102 I've made sure that `myPlugin` isn't nullptr.

Some free VST3 instruments to try are Surge.vst3 and TAL-NoiseMaker-64.vst3.

Note that VST3 _effects_ are working.

**Comment by dimentorium** [comment]
When using Tyrell as VST3 I get the following message in the DLL
type = k_meter!
VST3 got bad parameter 300000
MidiBankSelect 0

From this function in juce_AudioProcessorGraph.cpp
renderSequence->perform (buffer, midiMessages, graph.getPlayHead());

Which makes rendering super slow. This is not happening with the VST2 version

**Comment by dimentorium** [comment]
So after trying and debugging, I think there is a general issue in how the original code was created.
There is a note from the Juce creator here https://forum.juce.com/t/automatic-synthesiser-programmer/20757/5
that an asynchronous design is needed for plugins to work.

I also had short view on the tracktion engine, which might make things easier, but it does not support VST2 out of the box.
Think I am definately not smart enough for this task ;-)

**Comment by DBraun** [comment]
You're helping a lot, don't worry. If it needs to be asynchronous that would be a little frustrating. Tracktion might be a big departure too. For async there are some examples of using pybind11 with async

https://github.com/pybind/pybind11/blob/master/tests/test_async.py
https://github.com/pybind/pybind11/blob/master/tests/test_async.cpp

And then all of the audio processors could do setNonRealTime(false);

Maybe handling the playhead tracking (https://github.com/DBraun/DawDreamer/issues/21) could actually fix a bug here.

**Comment by dimentorium** [comment]
Did you ever post in the juce forum for help? Maybe someone has a simple hint ;-)

**Comment by DBraun** [comment]
Seems resolved
