### ISSUE TITLE
extra copies of libfaust in linux wheels

### ISSUE THREAD

**Issue by marclava** [DBraun/DawDreamer#147]
Linux wheels includes a dawdreamer.libs folder that is next to the dawdreamer folder (inside the site-packages folder used by pip install). The dawdreamer.so library is linked to the libraries inside dawdreamer.libs, including the one for Faust; there's two extra copies of the libfaust library (libfaust.so.2 and libfaust.so) inside the dawdreamer folder that should not be included. Each copy is 63MB.

Suggestion: move the dawdreamer.libs folder inside the dawdreamer folder, maybe renamed "libs".
Suggestion 2: shrink all included libraries using the "strip --strip-unneeded" command line.

**Comment by DBraun** [comment]
I've been using symbolic links to get the wheel to build. https://github.com/DBraun/DawDreamer/blob/4419dfdb92b18733c1ba1900bd948c023effba58/build_linux.sh#L7-L8

The Linux wheel is about 90 MB, which makes sense given that libfaust is 64 MB. Maybe the installed version of dawdreamer is taking up extra space, but my hunch so far is that the wheel itself doesn't contain duplicate information.

I've tried various things testing with WSL but after installing the wheel I get an error
```
/usr/local/lib/python3.10/dist-packages/dawdreamer/__init__.py:4: in <module>
    from .dawdreamer import *
E   ImportError: /usr/local/lib/python3.10/dist-packages/dawdreamer/dawdreamer.so: undefined symbol: _Z9boxFConst5STypeRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_
```
so the symbol boxFConst is missing.

To get this working we'd have to examine `setup.py` too: https://github.com/DBraun/DawDreamer/blob/4419dfdb92b18733c1ba1900bd948c023effba58/setup.py#L55-L79

PRs are welcome and they'll go through the GitHub actions.

**Comment by marclava** [comment]
Oops! ln creates s hard link; the option -s is required to create a symbolic link : 
`ln -s dawdreamer` ...
`ln -s thirdparty` ...

**Comment by marclava** [comment]
After the python module is installed I can safely remove the dawdreamer/libfaust*.so* files because dawdreamer/dawdreamer.so is linked to the libfaust*.so in ../dawdreamer.libs/

**Comment by DBraun** [comment]
The new linux wheel is 40 MB! I did `strip --strip-unneeded libfaust.so` like you said to the file in `thirdparty/libfaust`. Eventually I'd like to have libfaust dynamically downloaded from some server so that it's not committed as a file to the repo.
