### ISSUE TITLE
Weird rendering time consuming / midi rendering efficiency with Kontakt

### ISSUE THREAD

**Issue by ZhaoJY1** [DBraun/DawDreamer#15]
Hallo,

I encounter some rendering time consuming problem. In my own implement code, I wanted to render a midi file of approximately 4 minitues. And it just stucks at the `engine.render(end_time)` step. So I tested with following appended code for different intended rendering time length, and found that:
- when render for 5 seconds, rendering takes about 2 seconds
- when render for 10 seconds, rendering takes about 11 seconds
- when render for 20 seconds, rendering takes about  44-47 seconds

So, if render for some 300 seconds, the render time consuming would blow up and it simply looks like the program stucks.

I also tried with a real midi file which contains not so much "blank area", but got the same effect.

What could have gone wrong?

code:
```python
import numpy as np
import os
import pretty_midi
import soundfile as sf
import time

import dawdreamer as daw

SAMPLE_RATE = 44100
BUFFER_SIZE = 512
SYNTH_PLUGIN = os.path.abspath('testVST/DSK The Grand.dll') # plugin path

print('making engine...')
engine = daw.RenderEngine(SAMPLE_RATE, BUFFER_SIZE)

print('making processor...')
synth = engine.make_plugin_processor("synth", SYNTH_PLUGIN)

graph = [
    (synth, []),
]

synth.add_midi_note(60, 127, 0., 1.)  # note, velocity, start time sec, duration sec
synth.add_midi_note(67, 127, 0.5, .25)
# midi_path = os.path.abspath('MIDI/Track043_singleTrack.mid')
# pm = pretty_midi.PrettyMIDI(midi_path)
# end_time = pm.get_end_time()
# print('end time: {}'.format(end_time))
# synth.load_midi(midi_path)
print('loading graph...')
assert(engine.load_graph(graph))
print('rendering...')
start = time.time()
engine.render(10.)    # test e.g. 5, 10, 20... seconds
end = time.time()
print('Rendering time {}'.format(end - start))
audio = engine.get_audio()
audio = np.array(audio, np.float32).transpose()
sf.write('test_synth_basic.wav', audio, SAMPLE_RATE)

print("All Done!")
```

**Comment by DBraun** [comment]
Thank you very much for catching this. I made a few mistakes in the RecorderProcessor.h class. I will try to fix them now.

**Comment by DBraun** [comment]
I think I got it. Can you give the latest update a try? https://github.com/DBraun/DawDreamer/commit/5ab8e4bbf55a24f321443d0462799e1a96d0be14

I used your script and can render 120 seconds in 0.79 seconds.

**Comment by ZhaoJY1** [comment]
Hallo,

thanks a lot for so quick debuging. Yes, I tested it with my implementation, it works now fine and efficiently!!!

**Comment by DBraun** [comment]
Great!

**Comment by youknowwyz** [comment]
I have run your code to render a midi file, but I got an all zero WAV file. What could have gone wrong?
