### ISSUE TITLE
Import error after building wheel

### ISSUE THREAD

**Issue by psuskin** [DBraun/DawDreamer#154]
While following the Developer's Guide for Windows, everything worked fine, including the pip installation of the wheel. However, afterwards, when trying to import dawdreamer in python, I am met with the following error: ImportError: DLL load failed while importing dawdreamer: The specified module could not be found.

I am using (and built everything with) Python 3.8. Any help would be greatly appreciated.

**Comment by DBraun** [comment]
Sounds like you got it working? If you have recommend improvements to the documentation I'd be glad to hear them!
