### ISSUE TITLE
Uninitialized data input to plugin at start rendering

### ISSUE THREAD

**Issue by k9758901** [DBraun/DawDreamer#178]
We encounter uninitialized data input to VST3 plugin. We use IIR filter plugin and get diverged output.

When `RenderEngine::render` called, [the library reset plugin before start rendering](https://github.com/DBraun/DawDreamer/blob/v0.7.3/Source/RenderEngine.cpp#L290).
And in `PluginProcessor::reset`, [the library passing uninitialized buffer to plugin](https://github.com/DBraun/DawDreamer/blob/v0.7.3/Source/PluginProcessor.cpp#L281-L286).

This problem seems occurred from v0.7.2 ([diff](https://github.com/DBraun/DawDreamer/compare/v0.7.1..v0.7.2#diff-f807dacef9aefb753f5568051f0ff117da89edd11da14e293cd45768d1dd72e7))

Maybe buffer clear is a workaround for this problem. But, [as commented as in source](https://github.com/DBraun/DawDreamer/blob/v0.7.3/Source/PluginProcessor.cpp#L275-L276), we should not call `processBlock` in `PluginProcessor::reset`.

**Comment by DBraun** [comment]
Thanks for reporting and sorry for the bug. This will be fixed in the next release 0.7.4.

**Comment by k9758901** [comment]
Thanks for your quick response and fix!
