### ISSUE TITLE
Load dx7 syx files?

### ISSUE THREAD

**Issue by turian** [DBraun/DawDreamer#184]
I am trying to use the dexed VST and load_preset on the syx files. But nothing seems to load. Why?

**Comment by DBraun** [comment]
The load_preset method is only meant for fxp files and (I think) vstpreset files. `.syx` is its own category. However, I did just confirm that if you call `synth.open_editor()` you can select a syx file and get a different sound. That doesn't scale well to large amounts of syx files unfortunately.
