### ISSUE TITLE
Git tags for releases?

### ISSUE THREAD

**Issue by mxmilkiib** [DBraun/DawDreamer#19]
Hi. I'd like to include DawDreamer on https://libreav.org/updates but there aren't any git release tags for the project. Might these be possibly going forward? Any message attached to the git tag will appear in /releases.atom for this repo (or it can be done through the GH interface with Markdown).

**Comment by DBraun** [comment]
Good suggestion and thanks for including it. I will try to follow semantic versioning going forward. Here's a tagged release: https://github.com/DBraun/DawDreamer/releases/tag/v0.4.0

**Comment by DBraun** [comment]
I submitted it, but it's not up yet. Anyway, I'll do git tags going forward.

**Comment by mxmilkiib** [comment]
There has been an upstream backend bug where some saved feed entries go missing, but then are aggregated again (but then go again). I've manually reimported just now, it's a frustrating bug but I'll try keep an eye on the entry!
