### ISSUE TITLE
librosa 0.10.1 compatibility issue

### ISSUE THREAD

**Issue by heqi201255** [DBraun/DawDreamer#198]
I just upgraded librosa on my machine but it got SIGSEGV fault all the time for the "load()" function if the module also imports dawdreamer. Then I downgraded my librosa to 0.9.2 and the problem solved.

My specs:
Macbook Pro M1 Pro
macOS 14.3.1
dawdreamer 0.8.0
librosa installed using "conda install -c conda-forge librosa"

**Comment by DBraun** [comment]
Thanks for reporting. I think I will run the GitHub actions automated tests again and report back to you. DawDreamer has no dependencies, so I find the issue surprising. In the past I've seen compatibility issues with librosa, numpy and numba--not related to DawDreamer.

**Comment by DBraun** [comment]
Probably stale issue. The recent GitHub Actions runs have been using librosa 10.
