### ISSUE TITLE
Automatic real-time BPM analyser 

### ISSUE THREAD

**Issue by RustoMCSpit** [DBraun/DawDreamer#203]
Automatically display BPM of incoming audio / waveforms

https://bitwish.top/t/automatic-real-time-bpm-analyser/5427

**Comment by DBraun** [comment]
I don’t think this is a feature within the current aims of the project. I would recommend looking at https://github.com/mir-aidj/all-in-one for a non-real-time tempo detector. A non-real-time tempo detector will get better results than a real-time one, so for actual use within in a DAW I think higher quality is a higher priority than real-time.

**Comment by RustoMCSpit** [comment]
> I don’t think this is a feature within the current aims of the project. I would recommend looking at https://github.com/mir-aidj/all-in-one for a non-real-time tempo detector. A non-real-time tempo detector will get better results than a real-time one, so for actual use within in a DAW I think higher quality is a higher priority than real-time.

well non-real time could be used for waveforms already in the project while realtime for incoming audio streams
