### ISSUE TITLE
get_parameter_range() for Preset parameters?

### ISSUE THREAD

**Issue by turian** [DBraun/DawDreamer#206]
It's a bit tricky to decipher the metadata for preset parameters.

Pedalboard allows you to do something like this:
```
In [25]: instrument.parameters["decay"].ranges
Out[25]:
{(0, 0.001): 0.0,
 (0.001, 0.002): 0.1,
 (0.002, 0.003): 0.2,
 (0.003, 0.004): 0.3,
 (0.004, 0.005): 0.4,
 (0.005, 0.006): 0.5,
 (0.006, 0.007): 0.6,
 (0.007, 0.008): 0.7,
 (0.008, 0.009): 0.8,
 (0.009, 0.01): 0.9,
 (0.01, 0.011): 1.0,
 (0.011, 0.012): 1.1,
 (0.012, 0.013): 1.2,
 (0.013, 0.014): 1.3,
 (0.014, 0.015): 1.4,
 (0.015, 0.016): 1.5,
 (0.016, 0.017): 1.6,
 (0.017, 0.018): 1.7,
```

as well as assign by the string name, not the raw value.

Would it be possible to have this functionality in dawdreamer?

Right now the only workaround is just to comb the entire range of raw values and then find if the string has changed :\

**Comment by DBraun** [comment]
It's probably possible. I'll see what I can do this week.

**Comment by DBraun** [comment]
I can now make the ranges in C++, but I'll let users figure out how to assign by string name in Python since there are lot of edge cases. I will also have to fix the GitHub actions which broke due to staleness.

**Comment by turian** [comment]
Thank you. Question: The raw value (non string returned), will it keep drifting each time I set it? Or will it converge?

e.g. I set raw value. I get raw value, it's slightly different. If I set the second raw value again will it stay fixed? Or not guaranteed?

**Comment by DBraun** [comment]
This is my possibly wrong understanding, but I think these ranges are just superficial "low bit depth" text labels. In other words the label may go from .00 to .01 to .02 but the true values being used have much higher precision than two decimals.

With that said, are you observing some weird behavior that you'd like to have fixed?

**Comment by turian** [comment]
@DBraun Just for example, if you write a raw value and read it back, it can drift with VST plugins:

```
STEPS = 10000

n_parameters = len(synth.get_parameters_description())

for i in tqdm(list(range(n_parameters)), leave=False):
    name = synth.get_parameter_name(i)
    if name.startswith("MIDI CC") or name.startswith("CC"):
        continue
    for v in tqdm(list(range(STEPS)), leave=False):
        orig_raw_val = v / STEPS
        synth.set_parameter(i, orig_raw_val)
        # Read back the value just to be safe
        raw_value2 = synth.get_parameter(i)
        while raw_value2 != orig_raw_val:
            print(name, raw_value2)
            orig_raw_val = raw_value2
            synth.set_parameter(i, orig_raw_val)
            raw_value2 = synth.get_parameter(i)
```

I'm also not clear if the drift is deterministic or not.

**Comment by DBraun** [comment]
Python floats are 64-bit, but these VST parameters are 32-bit. Would that explain it? Can you paste some of the drift values?

Can you try this instead (not sure if it's related to `i` not corresponding to the actual parameter)
```python
STEPS = 10000

desc = synth.get_parameters_description()

for item in tqdm(desc, leave=False):
    name = item['name']
    i = item['index']
    if name.startswith("MIDI CC") or name.startswith("CC"):
        continue
    for v in tqdm(list(range(STEPS)), leave=False):
        orig_raw_val = v / STEPS
        synth.set_parameter(i, orig_raw_val)
        # Read back the value just to be safe
        raw_value2 = synth.get_parameter(i)
        while raw_value2 != orig_raw_val:
            print(name, raw_value2)
            orig_raw_val = raw_value2
            synth.set_parameter(i, orig_raw_val)
            raw_value2 = synth.get_parameter(i)
```

**Comment by DBraun** [comment]
Hi, I just wanted to leave a note for how to do this in the latest version:
```python
parameter_index = 10
search_steps = 1000  # default kwarg
convert=True  # default kwarg
range = synth.get_parameter_range(index, parameter_index, search_steps=search_steps, convert=convert)
```
`range` is a dictionary whose keys are tuples `(value1, value2)` where `value1<value2`. If `convert==True`, the values of the dictionary will floats, otherwise they will be left as strings for you to interpret.
