### ISSUE TITLE
Add parameter automation feature

### ISSUE THREAD

**Issue by DBraun** [DBraun/DawDreamer#5]
How can processor parameters such as the cutoff frequency of a filter be modified over time?

First, this seems connected to the block size. You probably need a small block size, maybe 128, out of 44100 samples in order to not perceive steppiness in changes in parameters.

Second, there’s the broader issue of the coding technique to implement this. Maybe every processor class needs to be modified to be able to hold an “animation object”, which could have any number of channels/samples. In the processBlock, rather than use protected variables, the processor would use a function that would lookup values from this animation object but fall back on values for missing channels.

Should the animations come from MIDI files or be python generated?

https://forum.juce.com/t/how-does-sample-accurate-host-plugin-automation-work/2117/13

**Comment by ethman** [comment]
Hey David, I believe this is typically called parameter automation in DAWs, which I believe JUCE has support for natively. Just some poking around led me to [this repo](https://github.com/getdunne/juce-AudioProcessorValueTreeStateTest), which relies on [this JUCE class](https://docs.juce.com/master/classAudioProcessorValueTreeState_1_1Parameter.html).

I would imagine the block size would need to be at least the same size as the buffer that the plug in uses. I could also imagine an integer multiple of the buffer size.

I think a nice API would be for the user to set the start time, end time, start parameter setting, end parameter setting, and interpolation method:

`synth.set_automation(10.0, 12.0, 50.0 ,100.0, 'linear')`

There's some corner cases here though. For instance, how do manage the state prior to 10.0 sec if it's not at `50.0`? I think what Logic Pro does is it will propagate `50.0` backwards to the beginning of the track if there is no other automation points set. If there are, then I think a default linear interpolation is set automatically. Another corner case is boolean values, for which interpolation doesn't make sense.

I don't think these are prohibitive, but they are opaque actions that are easy to communicate to a user when you have a GUI, but near impossible when it's all via an API so they're worth thinking about well.

**Comment by DBraun** [comment]
I've started a branch for this feature https://github.com/DBraun/DawDreamer/tree/feature/automation but it crashes here https://github.com/DBraun/DawDreamer/blob/93f911665c94b5e199fd721414b68bb2e2a79706/Source/CustomParameters.h#L15 and I'm not sure why...

Here's a console app trying to do the same kind of std::vector<float> copy.

[console_app_test.txt](https://github.com/DBraun/DawDreamer/files/5164075/console_app_test.txt)

It works fine, so I don't know why it's failing in the setAutomation function.

**Comment by DBraun** [comment]
The current version of the feature/automation branch (https://github.com/DBraun/DawDreamer/tree/feature/automation) has panning automation working! I'll try to get other parameters of other processors configured.

**Comment by DBraun** [comment]
closing with https://github.com/DBraun/DawDreamer/commit/b91818fac890dff2e51e227e98ea38e622c07b43
