### ISSUE TITLE
getTimeRatio in PlaybackWarpProcessor should be double, not bool

### ISSUE THREAD

**Issue by auryd** [DBraun/DawDreamer#81]
(Also, PlaybackWarpProcessor seems to always go into an infinite loop on render. I haven't been able to figure out why yet, so I hadn't filed an issue on that yet in case I'm just doing something wrong and it's expected behavior under some conditions?

For example, I can load an audio file into a PlaybackProcessor, and it works fine. But if I change the PlaybackProcessor to a PlaybackWarpProcessor, it infinite loops when I call engine.render.)

**Comment by DBraun** [comment]
Thanks. You're right about both. getTimeRatio will definitely get fixed in the next update, and I'm looking at playback warp processor again. There appears to be an issue when there isn't a warp file.

**Comment by DBraun** [comment]
Can you install the latest and take a look at https://github.com/DBraun/DawDreamer/blob/13cf58a8ee4413e553b057722f2c6b9e0b884951/tests/test_playbackwarp_processor.py#L120 for reference

**Comment by DBraun** [comment]
Closing. Please comment if there's still an issue.
