### ISSUE TITLE
Thread explosion after loading engine in a loop

### ISSUE THREAD

**Issue by noyuzrad** [DBraun/DawDreamer#88]
Seems like DawDreamer opens a new thread after each calling to  daw.RenderEngine(cfg.sample_rate, cfg.buffer_size).
I try to create large dataset from a synthesizer, which is 100% deterministic, so I load a new renderengine eachtime, since otherwise there are state buffers that make inconsistent sounds for the same parameters.
However, although I load into the same pythonic variable, it seems like we are running out of threads.
Is there any possibility to stop or kill dawdreamer threads?

I attach my code and the error.
![WhatsApp Image 2022-04-26 at 07 31 37](https://user-images.githubusercontent.com/57722241/165233339-9f4e5021-fc96-4b40-8e98-760c3fa69a45.jpeg)
![image](https://user-images.githubusercontent.com/57722241/165233398-04f5ff64-8efa-4947-87ab-f95d60d7b329.png)

**Comment by DBraun** [comment]
Thanks I'll look into this soon. Just to be clear did you try putting the RenderEngine creation outside of the loop while keeping synth creation inside?

**Comment by DBraun** [comment]
Sorry for this bug. It's the same as in https://github.com/DBraun/DawDreamer/issues/1 I hope to fix it but it's been challenging for a while.

**Comment by DBraun** [comment]
Can you try out 0.6.5 and let me know if you see an issue?

**Comment by DBraun** [comment]
Please re-open if an issue persists.
