### ISSUE TITLE
Windows Python 3.10 isn't on PyPI pip

### ISSUE THREAD

**Issue by samuelbraun04** [DBraun/DawDreamer#94]
I'm trying to install dawdreamer by doing:

`pip install dawdreamer`

but I'm getting the following error:

`ERROR: Could not find a version that satisfies the requirement dawdreamer (from versions: none)
ERROR: No matching distribution found for dawdreamer`

----------------------------------------------------------------------------------------------------

So, since the normal pip install method didn't work, I tried to install the package by doing:

`pip install dawdreamer-0.6.7-cp39-cp39-win_amd64.whl`

but then I got the following error:

`WARNING: Requirement 'dawdreamer-0.6.7-cp39-cp39-win_amd64.whl' looks like a filename, but the file does not exist
ERROR: dawdreamer-0.6.7-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.`

----------------------------------------------------------------------------------------------------

Then, I tried running the 'dawdreamer-0.6.7-cp39-cp39-win_amd64.whl' file, but then I got the following error:

`ERROR: dawdreamer-0.6.7-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.`

----------------------------------------------------------------------------------------------------

This isn't happening when I pip install any other packages (I can pip install other packages just fine), so I don't know why this problem arises when I try and install dawdreamer. FYI I'm a bit of a beginner so I'm sorry if I'm missing something obvious.

I'm using Python 3.10.4 on Windows 10.

**Comment by DBraun** [comment]
Hi thanks for trying it out. The pip wheels don’t include Python 3.10 yet. I encountered an issue with building for 3.10 a long time ago (I don’t remember what), and I haven’t gotten around to trying again. I think if you try with 3.7-3.9 you will have better luck.
